In [12]:
import numpy as np

y = np.arange(9)
y.shape = [3, 3]
y = y.transpose()
print(y)

z = np.zeros((6,6), dtype=int)
print(z)

[[0 3 6]
 [1 4 7]
 [2 5 8]]
[[0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]]


In [17]:
import numpy as np

x = np.arange(4).reshape(2,2)
y = np.arange(4,8).reshape(2,2)

h = np.hstack((x,y))
v = np.vstack((x,y))

print(x)
print(y)
print(h)
print(v)

[[0 1]
 [2 3]]
[[4 5]
 [6 7]]
[[0 1 4 5]
 [2 3 6 7]]
[[0 1]
 [2 3]
 [4 5]
 [6 7]]


In [20]:
w = np.concatenate((x,y), axis=1)
print(w)

[[0 1 4 5]
 [2 3 6 7]]


In [22]:
dstack = np.dstack((x,y))
print(dstack)

[[[0 4]
  [1 5]]

 [[2 6]
  [3 7]]]
